server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/custom_database
    username: postgres
    password: password
    hikari:
      connection-timeout: 45000
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 120000
      auto-commit: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/custom-realm
          jwk-set-uri: http://localhost:8080/realms/custom-realm/protocol/openid-connect/certs
