server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
#    hibernate:
#      ddl-auto: update
  datasource:
    url: jdbc:postgresql://todo-app-db-lb:32032/custom_database
    username: postgres
    password: password
    hikari:
      connection-timeout: 45000
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 120000
      auto-commit: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK}/realms/custom-realm
          jwk-set-uri: http://${KEYCLOAK}/realms/custom-realm/protocol/openid-connect/certs
