version: '3'

services:

#  todo-app:
#    image: 'todo-app:latest'
#    container_name: todo-app
#    ports:
#      - "8081:8081"
#    depends_on:
#      - todo-app-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://todo-app-db:5432/custom_database
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=password
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - KEYCLOAK=todo-app-keycloak-svc


  todo-app-db:
    image: 'postgres:16.1-alpine'
    container_name: todo-app-db-dc
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=custom_database
    ports:
      - "32032:5432"


  todo-app-keycloak-db:
    image: 'postgres:16.1-alpine'
    container_name: todo-app-keycloak-db-dc
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak_database


  todo-app-keycloak-svc:
    image: 'keycloak/keycloak:22.0.5'
    container_name: todo-app-keycloak-svc-dc
    command: -v start-dev --import-realm
    volumes:
      - ../../src/main/resources/keycloak:/opt/keycloak/data/import
    depends_on:
      - todo-app-keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://todo-app-keycloak-db:5432/keycloak_database
      KC_DB_USERNAME: postgres
#      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
#      KC_METRICS_ENABLED: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "32061:8080"
